name: KillEntity
version: 1.0.0
api: [5.0.0]
author: swevagin
main: swevagin\KillEntity\Main
description: A plugin that adds money to a player when they kill an entity.


depend:
- BedrockEconomy

permissions:
  killentity.plugin:
    default: true
