#format => name_entity: money
animals:
- Zombie: 10
- Villager: 20
# 1 for sending pop-ups
# 2 for sending messages
# 3 to turn off message notifications
message: 1
# enter the percentage of the money amount that you want the player to lose when they die in combat
# enter 0 for deactive this feature
percent: 50
# enter the name world that you want to be deactivated
x1: 31
y1: 72
z1: -23

x2: 45
y2: 72
z2: -10



worlds:
- world

# permissions: killentity.plugin
