#format => name_entity: money
animals:
- Zombie: 10
- Villager: 20
# 1 for sending pop-ups
# 2 for sending messages
# 3 to turn off message notifications
message: 1
# enter the percentage of the money amount that you want the player to lose when they die in combat
# enter 0 for deactive this feature
percent: 50
# enter the name world that you want to be deactivated
x: 31
y: 42
z: -23
worlds:
- world

# permissions: killentity.plugin
