#format => name_entity: money
animals:
- Zombie: 10
- Villager: 20
# 1 for sending pop-ups
# 2 for sending messages
# 3 to turn off message notifications
message: 1
# enter the name world that you want to be activated
worlds:
- world

# permissions: killentity.plugin
