#format => name_entity: money
animals:
- Zombie: 10
- Villager: 20
# 1 for sending pop-ups
# 2 for sending messages
# 3 to turn off message notifications
message: 2
# enter the percentage of the money amount that you want the player to lose when they die in combat.
percent: 50
# enter the name world that you want to be deactivated
worlds:
- world

# permissions: killentity.plugin
